name: Hello World Workflow

on: push

jobs:
  my_first_job:
   name: My first job
   runs-on: ubuntu-latest

   steps:
      - name: Greeting
        run: echo "Hello Paras! GitHub Action Running"

  my_second_job:
   name: My second job
   needs: My first job
   runs-on: windows-latest
   
   steps:
    - name: Greeting
      run: echo "Hello Devops Teams"
      
    
  
  
